#!/bin/bash

function scr {
    let deletefile=0
    let quiet=1

    while [ -n "$1" ]
    do
        case "$1" in
            -d) deletefile=1 ;;
            -q) quiet=0 ;;
            -r) shift
                break
                ;;
            *) echo "$1 is not an option"
                ;;
        esac
        shift
    done

    word=$1
    wget -q https://rifmus.net/rifma/$word
    
    touch 'tmp-file'
    chmod 777 tmp-file

    squa=${word:((${#word}-2)):2}

    cat $word | grep '<li>' | sed -e "s%<li>%%" | sed -e "s%</li>%%" | sed -e "s/ //g" | sed -e "/^$/d" 1> tmp-file
    
    cat tmp-file | sed -e "/.$squa$/d" > $word
    
    chmod 777 $word
    
    ./getr2 $word
    
    ./zapp 1> gzun
    
    chmod 777 gzun
    rm zapp

    cat gzun | grep '<li>' | sed -e "s%<li>%%" | sed -e "s%</li>%%" | sed -e "s/ //g" | sed -e "/^$/d" 1> tmp-file
    
    cat tmp-file | sed -e "/.$squa$/d" 1>> $word

    rm gzun
    
    rm tmp-file

    if [ "$quiet" == 1 ]
        then cat $word
    fi

    if [ "$deletefile" == 1 ]
    then 
        rm $word
    fi
}
##########################FUNCTION##########################

if [ "$#" -eq 1 ]
    then scr "-r" "$1"
    elif [ "$#" -eq 2 ]
        then

###########

word1=$1
word2=$2
scr "-q" "-r" "$word1" 
scr "-q" "-r" "$word2" 

echo "$word1" "$word2"

let c1=$(wc -l $word1 | sed -e "s/$word1//")
let c2=$(wc -l $word2 | sed -e "s/$word2//")

let i=1

echo "$c1" "$c2"

while [ $i -le $c1 ]
do
    #echo "$i"    
    let j=1    
    a1=$(sed -n "${i}p" < $word1)    
    while [ $j -le $c2 ]
    do      
        #echo "$j"        
        a2=$(sed -n "${j}p" < $word2)
        if [ $a1 == $a2 ]
            then
            echo "$a1"
        fi
        let j=$j+1
    done    
    let i=$i+1
done

rm $word1
rm $word2

#######

fi
